function b = asymm_right
%ASYMM_RIGHT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Oct-2023 14:20:12

% FIR constrained least-squares Bandpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N       = 101;   % Order
Fc1     = 900;   % First Cutoff Frequency
Fc2     = 1100;  % Second Cutoff Frequency
Dstop1U = 0.01;  % Upper Stopband Attenuation
Dstop1L = 0.01;  % Lower Stopband Attenuation
DpassU  = 0.1;   % Upper Passband Ripple
DpassL  = 0.1;   % Lower Passband Ripple
Dstop2U = 400;   % Upper Stopband Attenuation
Dstop2L = 400;   % Lower Stopband Attenuation

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc1 Fc2 Fs/2]/(Fs/2), [0 1 0], [Dstop1U 1+DpassU ...
            Dstop2U], [-Dstop1L 1-DpassL -Dstop2L]);
Hd = dfilt.dffir(b);

% [EOF]